config/routes.rb
Rails.application.routes.draw do
  resources :activities
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/about', to: 'welcome#about'
  get '/summary', to: 'activities#summary'
  get '/summary-all', to: 'activities#summary_all'
  get '/list', to: 'activities#list'
end

app/models/activity.rb
class Activity < ApplicationRecord
  attr_accessor :hours, :minutes

  before_validation :duration_to_minutes
  after_find :duration_to_hours_and_minutes # for partial updates to work

  enum activity_type: [:running, :walking, :hiking, :swimming, :biking, :skating, :horse_back_riding, :resistance, :balance_ball, :trx, :pint_lifting ]

  validates :activity_type, inclusion: {
      in: activity_types,
      message: "Valid activity is required"
  }
  validates :duration, numericality: {greater_than: 0, :message => 'needs to be at least 1 minute'}
  validate :activity_date_valid_range

  def self.all_for_user(user: required)
    forUser(user.id).order('activity_date desc')
  end

  def self.in_range_for_user(user: required, date_range: required)
    inRange(date_range: date_range)
      .forUser(user.id)
      .order('activity_date asc')
  end

  private

  scope :inRange, ->(date_range:){where('activity_date >= ?', date_range.start_date).where('activity_date <= ?', date_range.end_date)}

  scope :forUser, -> (userId) { where('user_id = ?', userId) }

  def activity_date_valid_range
    if activity_date.nil? || activity_date > Date.current
      errors.add(:activity_date, "can't be in the future")
    end
  end

  def duration_to_minutes
    self.duration = hours.to_i * 60 + minutes.to_i
  end

  def duration_to_hours_and_minutes
    self.hours = duration.to_i / 60
    self.minutes = duration.to_i % 60
  end

  belongs_to :user

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :require_ownership, only: [:edit, :update, :destroy]
  before_action :require_authorization, only: [:index, :list, :summary, :summary_all, :show]

  # GET /activities
  # GET /activities.json
  def index
    @weeks_ago = params[:weeks_ago].to_i || 0
    date_range = DateRange.new.week_from_weeks_ago(@weeks_ago)
    @activities = Activity.in_range_for_user(date_range: date_range, user: current_user)
  end

  # GET /list
  # GET /list.json
  def list
    @activities = Activity.all_for_user(user: current_user)
    respond_to do |format|
      format.html
      format.json { render :index, status: :ok }
    end
  end

  # GET /summary
  # GET /summary.json
  def summary
    @weeks_ago = params[:weeks_ago].to_i || 0
    date_range = DateRange.new.week_from_weeks_ago(@weeks_ago)
    @summary = ActivitySummary.new(
      activities: Activity.in_range_for_user(user: current_user, date_range: date_range)
    )
  end

  # GET /summary-all
  # GET /summary-all.json
  def summary_all
    @summary = ActivitySummary.new(
      activities: Activity.all_for_user(user: current_user)
    )
    # reuse summary json template
    respond_to do |format|
      format.html
      format.json { render :summary, status: :ok }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    # links to individual records should be bookmarkable
    # and available via login splash
    # so the auth error should only be raised
    # after the login if the user is wrong
    require_ownership
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
  end

  def require_authorization
    redirect_to(user_session_path) unless user_signed_in?
  end

  def require_ownership
    raise ApplicationController::NotAuthorized unless @activity.user == current_user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def activity_params
    params.require(:activity).permit(:user_id, :activity_type, :activity_date, :hours, :minutes)
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper

  def render_timespan(total_mins)
    "#{total_mins_to_partial_hrs(total_mins)}h #{total_mins_to_partial_mins(total_mins) % 60}min"
  end

  def total_mins_to_partial_hrs(total_mins)
    total_mins.to_i / 60
  end

  def total_mins_to_partial_mins(total_mins)
    total_mins.to_i % 60
  end

  def render_date(date)
    date.strftime("%a, %d %b %Y")
  end

  def render_week_title(weeks_ago)
    week = DateRange.new.week_from_weeks_ago(weeks_ago)
    "#{render_date(week.start_date)} - #{render_date(week.end_date)}"
  end

  def date_to_weeks_ago(date)
    DateRange.date_to_weeks_ago(date)
  end

end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation" class="alert alert-warning text-center" role="alert">
      <p>Please correct <%= pluralize(activity.errors.count, "error") %>:</p>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group <%= css_invalid(activity.errors.include? :activity_type) %>">
    <%= form.label :activity_type %>
    <%= form.select :activity_type, Activity.activity_types.keys.map {|activity_type| [activity_type.titleize,activity_type]} %>
  </div>

  <div class="field form-group <%= css_invalid(activity.errors.include? :activity_date) %>">
    <%= form.label :activity_date %>
    <%= form.date_select :activity_date %>
  </div>

  <div class="field form-group duration <%= css_invalid(activity.errors.include? :duration) %>">
    <%= form.label :hours %>
    <%= form.number_field :hours %>
    <%= form.label :minutes %>
    <%= form.number_field :minutes%>
  </div>

  <div class="actions py-3 text-center">
    <%= form.submit "Save activity", :class => "btn btn-secondary" %>
  </div>
<% end %>

app/views/activities/_list.html.erb
<table class="table table-bordered">
  <thead class="thead-light">
  <tr>
    <th>Activity type</th>
    <th>Activity date</th>
    <th>Duration</th>
    <th class="text-center">
      <%= link_to 'New', new_activity_path, :class => "btn btn-secondary"  %>
    </th>
  </tr>
  </thead>

  <tbody>
  <% activities.each do |activity| %>
      <tr>
        <td><%= activity.activity_type.titleize %></td>
        <td><%= render_date(activity.activity_date) %></td>
        <td><%= render_timespan(activity.duration) %></td>
        <td>
          <nav class="nav justify-content-around">
            <%= link_to activity, :class => "item nav-link btn btn-light rounded-circle" do %>
                <i class="fa fa-eye"></i>
            <% end %>
            <%= link_to edit_activity_path(activity), :class => "item nav-link  btn btn-light rounded-circle" do %>
                <i class="fa fa-edit"></i>
            <% end %>
            <%= link_to activity, method: :delete, data: { confirm: 'Are you sure?' }, :class => "item nav-link btn btn-light rounded-circle" do %>
                <i class="fa fa-times"></i>
            <% end %>
          </nav>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/activities/_summary.html.erb
<table class="table table-bordered">
  <thead class="thead-light">
  <th>Activity</th>
  <th>Total per week</th>
  </thead>
  <% @summary.totals_by_type.each do |activity, duration| %>
      <tr>
        <td><%= activity.to_s.titleize %></td>
        <td><%= render_timespan(duration) %></td>
      </tr>
  <% end %>
  <tr class="font-weight-bold">
    <td>All activities</td>
    <td><span class="badge badge-secondary"><%= render_timespan(@summary.total) %></span></td>
  </tr>
</table>

app/views/activities/_weekly_header.html.erb
<p class="text-center">
  <%= render_week_title(weeks_ago) %>
</p>

<nav aria-label="by-week-pagination" class="nav justify-content-center">
  <ul class="pagination">
    <li class="page-item <%= css_active(@weeks_ago == 2) %>">
      <%= link_to '2 weeks ago', { weeks_ago: 2 }, :class => "page-link" %>
    </li>
    <li class="page-item <%= css_active(@weeks_ago == 1) %>">
      <%= link_to 'Last week', { weeks_ago: 1 }, :class => "page-link" %>
    </li>
    <li class="page-item <%= css_active(@weeks_ago == 0) %>">
      <%= link_to 'This week', { weeks_ago: 0 }, :class => "page-link" %>
    </li>
  </ul>
</nav>

app/views/activities/edit.html.erb
<div id="notice" class="<%= notice.present? ? 'alert alert-success' : ''%>" role="alert"><%= notice %></div>
<% if @activity.errors.any? %>
    <div class="alert alert-warning text-center" role="alert">
      Coudn't save activity.
    </div>
<% end %>
<section class="py-5 d-flex justify-content-center">
  <div class="card" style="width: 25rem;">
    <div class="card-body">
      <h3 class="card-title text-center pb-2">Editing Activity</h3>
      <%= render 'form', activity: @activity %>
      <nav class="nav justify-content-center">
        <%= link_to 'Show', @activity, :class => "item nav-link border-right" %>
        <%= link_to 'View All', activities_path(:weeks_ago => date_to_weeks_ago(@activity.activity_date)), :class => "nav-item nav-link" %>
        <%= link_to 'Delete', @activity, method: :delete, data: { confirm: 'Are you sure?' }, :class => "item nav-link border-left"%>
      </nav>
    </div>
  </div>
</section>

app/views/activities/index.html.erb
<div id="notice" class="text-center <%= notice.present? ? 'alert alert-success' : ''%>" role="alert"><%= notice %></div>
<section class="py-5 container position-relative">
  <%= link_to 'All Time', list_path, :class => "position-absolute auxiliary-link-right badge badge-light" %>
  <%= link_to 'Weekly', activities_path, :class => "position-absolute auxiliary-link-left badge badge-primary" %>
  <h1 class="text-center">Activities</h1>

  <%= render 'weekly_header', weeks_ago: @weeks_ago %>

  <%= render 'list', activities: @activities %>

  <nav aria-label="summary-links" class="nav justify-content-center">
    <%= link_to 'Summary', summary_path({ weeks_ago: @weeks_ago }), :class => "nav-item nav-link" %>
  </nav>

</section>

app/views/activities/list.html.erb
<div id="notice" class="text-center <%= notice.present? ? 'alert alert-success' : ''%>" role="alert"><%= notice %></div>
<section class="py-5 container position-relative">
  <%= link_to 'All Time', list_path, :class => "position-absolute auxiliary-link-right badge badge-primary" %>
  <%= link_to 'Weekly', activities_path, :class => "position-absolute auxiliary-link-left badge badge-light" %>
  <h1 class="text-center">Activities</h1>

  <%= render 'list', activities: @activities %>

  <nav aria-label="summary-links" class="nav justify-content-center">
    <%= link_to 'Summary', summary_all_path, :class => "nav-item nav-link" %>
  </nav>

</section>

app/views/activities/new.html.erb
<div id="notice" class="<%= notice.present? ? 'alert alert-success' : ''%>" role="alert"><%= notice %></div>
<% if @activity.errors.any? %>
    <div class="alert alert-warning text-center" role="alert">
      Coudn't save activity.
    </div>
<% end %>
<section class="py-5 d-flex justify-content-center">
  <div class="card" style="width: 25rem;">
    <div class="card-body">
      <h3 class="card-title text-center pb-2">New Activity</h3>

        <%= render 'form', activity: @activity %>

      <nav class="nav justify-content-center">
        <%= link_to 'View All', activities_path, :class => "nav-item nav-link" %>
      </nav>
    </div>
  </div>
</section>

app/views/activities/show.html.erb
<div id="notice" class="text-center <%= notice.present? ? 'alert alert-success' : ''%>" role="alert"><%= notice %></div>
<section class="py-5 d-flex justify-content-center">
  <div class="card" style="width: 25rem;">
    <div class="card-body">
      <h3 class="card-title text-center pb-2">Activity Log</h3>

      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <strong>Activity type:</strong>
          <%= @activity.activity_type.titleize %>
        </li>
        <li class="list-group-item">
          <strong>Activity date:</strong>
          <%= @activity.activity_date %>
        </li>
        <li class="list-group-item">
          <strong>Duration:</strong>
          <%= render_timespan(@activity.duration) %>
        </li>
      </ul>

      <nav class="nav justify-content-center mt-4">
        <%= link_to 'Edit', edit_activity_path(@activity), :class => "item nav-link border-right" %>
        <%= link_to 'View All', activities_path(:weeks_ago => date_to_weeks_ago(@activity.activity_date)), :class => "nav-item nav-link" %>
        <%= link_to 'Delete', @activity, method: :delete, data: { confirm: 'Are you sure?' }, :class => "item nav-link border-left"%>
      </nav>

    </div>

  </div>
</section>

app/views/activities/summary.html.erb
<div id="notice" class="text-center <%= notice.present? ? 'alert alert-success' : ''%>" role="alert"><%= notice %></div>
<section class="py-5 container position-relative">
  <%= link_to 'All Time', summary_all_path, :class => "position-absolute auxiliary-link-right badge badge-light" %>
  <%= link_to 'Weekly', summary_path, :class => "position-absolute auxiliary-link-left badge badge-primary" %>
  <h1 class="text-center">Summary</h1>

  <%= render 'weekly_header', weeks_ago: @weeks_ago %>

  <%= render 'summary', summary: @summary %>

  <nav class="nav justify-content-center">
    <%= link_to 'Activities', activities_path({ weeks_ago: @weeks_ago }), :class => "nav-item nav-link" %>
  </nav>

</section>

app/views/activities/summary_all.html.erb
<div id="notice" class="text-center <%= notice.present? ? 'alert alert-success' : ''%>" role="alert"><%= notice %></div>
<section class="py-5 container position-relative">
  <%= link_to 'All Time', summary_all_path, :class => "position-absolute auxiliary-link-right badge badge-primary" %>
  <%= link_to 'Weekly', summary_path, :class => "position-absolute auxiliary-link-left badge badge-light" %>
  <h1 class="text-center">Summary</h1>

  <p class="text-center">
    <%= "#{render_date(@summary.range_start)} - #{render_date(@summary.range_end)}" %>
  </p>

  <%= render 'summary', summary: @summary %>

  <nav class="nav justify-content-center">
    <%= link_to 'Activities', list_path, :class => "nav-item nav-link" %>
  </nav>

</section>