config/routes.rb
Rails.application.routes.draw do
  resources :activities
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/about', to: 'welcome#about'
  get '/summary', to: 'activities#summary'
  get '/summary-all', to: 'activities#summary_all'
  get '/list', to: 'activities#list'
end

app/views/layouts/_footer.html.erb
<!-- Footer section -->
<footer class="footer bg-dark">
  <div class="container">

    <div class="row text-center pt-5">

      <div class="col-12 col-md-5 social-media text-md-right">
        <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
        <a href="https://twitter.com/"><i class="fa fa-twitter"></i></a>
        <a href="https://www.instagram.com/?hl=en"><i class="fa fa-instagram"></i></a>
      </div>
      <div class="col-12 col-md-7 mt-5 mt-md-4 text-md-center">
        <h4>
          <ul class="nav">
            <li class="nav-item pr-lg-5 welcome">
          <%= link_to 'Welcome', root_path, :class => "nav-link welcome" %>
            </li>
            <li class="nav-item pr-lg-5 about">
          <%= link_to 'About', about_path, :class => "nav-link about" %>
            </li>
          </ul>
        </h4>
      </div>

    </div>


    <div class="row p-5 px-md-0 d-block">
      <p class="text-left text-primary">Copyright and small print</p>
      <small class="text-left text-muted d-block">
        Nisl suscipit adipiscing bibendum est ultricies integer quis auctor elit. Ornare massa eget egestas purus viverra. Egestas fringilla phasellus faucibus scelerisque eleifend. Molestie nunc non blandit massa enim nec dui. Arcu non odio euismod lacinia at quis risus sed. Consectetur lorem donec massa sapien faucibus. Leo in vitae turpis massa sed elementum tempus egestas. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. Morbi tempus iaculis urna id volutpat lacus laoreet. In nibh mauris cursus mattis molestie a iaculis. Nisl pretium fusce id velit ut tortor pretium viverra.
      </small>
      <small class="text-left text-muted d-block mt-4">
        Ac placerat vestibulum lectus mauris ultrices eros in cursus. Feugiat pretium nibh ipsum consequat nisl. Sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Donec et odio pellentesque diam volutpat commodo sed. Ac ut consequat semper viverra nam libero justo laoreet. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Lobortis scelerisque fermentum dui faucibus in ornare. Quis viverra nibh cras pulvinar mattis nunc sed blandit. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Sit amet volutpat consequat mauris nunc congue nisi. Vel facilisis volutpat est velit egestas dui id. Id ornare arcu odio ut sem. Nibh cras pulvinar mattis nunc. Enim nulla aliquet porttitor lacus luctus accumsan tortor. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Eu scelerisque felis imperdiet proin fermentum.
      </small>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-sm navbar-dark bg-dark p-3" id="topbar">
  <div class="container my-0 py-0">
    <a class="navbar-brand text-expanded font-weight-bold d-md-none" href="#">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav scrollNav">
        <% if user_signed_in? %>
            <li class="nav-item pr-lg-5 activities">
              <%= link_to activities_path, :class => "nav-link text-expanded" do %>
                  <%= content_tag :span, "Your activities", :class => "logoLink" %>
                  <%= content_tag :span, "(current)", :class => "sr-only" %>
              <% end %>
            </li>
            <li class="nav-item pr-lg-5 summary">
              <%= link_to summary_path, :class => "nav-link text-expanded" do %>
                  <%= content_tag :span, "Summary" %>
              <% end %>
            </li>
        <% else %>
          <li class="nav-item pr-lg-5 welcome">
            <%= link_to root_path, :class => "nav-link text-expanded" do %>
                <%= content_tag :span, "Welcome", :class => "logoLink" %>
                <%= content_tag :span, "(current)", :class => "sr-only" %>
            <% end %>
          </li>
          <li class="nav-item pr-lg-5 about">
            <%= link_to about_path, :class => "nav-link text-expanded" do %>
                <%= content_tag :span, "About" %>
            <% end %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <%  if user_signed_in? %>
          <li class="nav-item pl-lg-5 account">
            <%= link_to 'Signed in as ' + current_user.name, edit_user_registration_path, :class => "nav-link text-expanded" %>
          </li>
          <li class="nav-item pl-lg-5">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, :class => "nav-link text-expanded" %>
          </li>
        <% else %>
          <li class="nav-item pl-lg-5 signin">
            <%= link_to 'Sign in', new_user_session_path, :class => "btn btn-secondary" %>
          </li>
          <li class="nav-item pl-lg-5 signup">
            <%= link_to 'Sign up', new_user_registration_path, :class => "nav-link text-expanded" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= "#{controller_name} #{action_name}" %>">
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>